server:
  port: 8763

spring:
  application:
    name: store-web-console
  rocketmq:
    namesrv_address: 140.143.12.110:9876
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

