server:
  port: 8764

spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-console/hi
      serviceId: store-web-console
    api-b:
      path: /api-auth/hi
      serviceId: store-service-auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
